First round of README tweaks
paritytech/ledgeracio pull request #33
Opened 2020-09-04 08:44 UTC by dvdplm

Minor tweaks; we still need to work on the introduction and provide a description of the context and intended use case, explain the relationship to zondax etc.

2020-09-04 11:53 UTC, wpank approved these changes

2020-09-04 16:48 UTC, DemiMarie requested changes
Ledgeracio does not use the term “whitelist”.  Otherwise, only some minor nits.

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +should work as long as their RPC endpoints match Kusama/Polkadot's.
```suggestion
should work as long as their RPC API matches Kusama/Polkadot's.
```

Ledgeracio must work with any RPC endpoint URL, so long as it is wire-compatible.

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +That said, it works on macOS and other Unix-like systems that provide the
Have you tested it on macOS?

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +signed allowlists and operate on the whitelisted accounts.  It will be uploaded
```suggestion
signed allowlists and operate on the allowed accounts.  It will be uploaded
```

Ledgeracio does not use the term “whitelist”.

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +It is primarily intended for debugging. Requires a network connection.
```suggestion
It is primarily intended for debugging.  Requires a network connection.
```

Extremely minor style nit: Ledgeracio uses two spaces after a period.

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +stdout.  It is primarily intended for debugging. Requires a network connection.
```suggestion
stdout.  It is primarily intended for debugging.  Requires a network connection.
```

Ditto

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +nominator derivation path. Requires a network connection.  The following
```suggestion
nominator derivation path.  Requires a network connection.  The following
```

Ditto

2020-09-04 16:48 UTC, DemiMarie commented on README.md
> +This command handles validator operations. Requires a network connection.  It
```suggestion
This subcommand handles validator operations.  It requires a network connection, and
```

2020-09-05 19:58 UTC, DemiMarie approved these changes
Looks good, thanks!

2020-09-05 19:58 UTC, merged

2020-09-07 06:58 UTC, dvdplm commented on README.md
> +That said, it works on macOS and other Unix-like systems that provide the
I have yes.

2020-09-07 06:59 UTC, dvdplm commented on README.md
> +signed allowlists and operate on the whitelisted accounts.  It will be uploaded
Good call and good riddance. :)

2020-09-07 07:02 UTC, dvdplm commented on README.md
> +It is primarily intended for debugging. Requires a network connection.
I noticed that! Hopefully one day we can sit down and debate that choice properly! ;)

I'll stick to the 2x:space: rule from here on out, but yeah, I do it under protest!